# Week 8 Project

## Leqi Zhao

<!-- leave this material as is -->
Compiled on `r date()`.

```{r include = FALSE}
library(DataComputing)
library("ggdendro", lib.loc="/Library/Frameworks/R.framework/Versions/3.2/Resources/library")
```
<!-- put your content after this line -->

## Example

```
Dists <- dist(mtcars)
Dendrogram <- hclust(Dists)
ddata <- dendro_data(Dendrogram)
ggdendrogram(Dendrogram, rotate = TRUE) +
  geom_text(data = ddata$labels, aes(x=x, y=y, label = label), vjust = 0) 
```


## Wrangling the Genetics Data

```{r}
Narrow <- NCI60 %>%
  gather(value=expression, key=cellLine, -Probe) %>%
  group_by(Probe, cellLine) %>%
  summarise(expression = mean(expression)) %>% 
  ungroup()
```

```{r}
keep <- 500
Best <-
  Narrow %>%
  group_by(Probe) %>%
  summarise(spread = sd(expression)) %>%
  arrange(desc(spread)) %>%
  mutate(i = row_number()) %>%
  head(keep)
Randomized <-
  Narrow %>%
  mutate(Probe = shuffle(Probe)) %>%
  group_by(Probe) %>%
  summarise(spread = sd(expression)) %>%
  arrange(desc(spread)) %>%
  mutate(i = row_number()) %>%
  head(keep)
Best %>% 
  ggplot(aes(x=i, y=spread)) + 
  geom_line() +
  geom_line(data=Randomized, color="red", size=1, alpha=.5)

```

```{r}
Keepers <-
  Narrow %>% group_by(Probe) %>%
  filter(sd(expression) > 4.5)
```

```{r}
Keepers <-
  Keepers %>%
  spread(key=Probe, value=expression)
scale_colour_discrete <- function(...) scale_colour_hue(...)
```

```{r}
Dists <- dist(select(Keepers,-cellLine))
Dendrogram <- hclust(Dists)
ddata <- dendro_data(Dendrogram)
ggdendrogram(Dendrogram, rotate = TRUE) +
  geom_text(data = ddata$labels, aes(x=x, y=y, label = label), vjust = 0) 
```

